#application: testbook
#application: testbookte
application: notaworddictionary
version: 1
runtime: python
api_version: 1



# Datastore Admin handler
#builtins:
#- datastore_admin: on
#- remote_api: on

handlers:

# most common mistake is puting the remote_api after the "catch all" handler
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
# i think it is admin for the dev server
#  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /images
  static_dir: images
  
- url: /pics
  static_dir: pics

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: main.py
  
